"use strict";
var console_1 = require("./console");
exports.toggleDevTools = console_1.toggleDevTools;
exports.clearConsole = console_1.clearConsole;
exports.openDevTools = console_1.openDevTools;
var editor_1 = require("./editor");
exports.getEditor = editor_1.getEditor;
var file_1 = require("./file");
exports.openFolder = file_1.openFolder;
exports.open = file_1.open;
exports.save = file_1.save;
exports.scroll = file_1.scroll;
var write_1 = require("./write");
exports.set = write_1.set;
exports.insert = write_1.insert;
var writeFile_1 = require("./writeFile");
exports.writeFileFromContent = writeFile_1.writeFileFromContent;
exports.writeFileFromFile = writeFile_1.writeFileFromFile;
//# sourceMappingURL=index.js.map