export const COMPLETE_PAGE = 'COMPLETE_PAGE';
export const COMPLETE_TUTORIAL = 'COMPLETE_TUTORIAL';
export const PAGE_SET = 'PAGE_SET';
export const PROGRESS_LOAD = 'PROGRESS_LOAD';
export const PROGRESS_PAGE_POSITION_LOAD = 'PROGRESS_PAGE_POSITION_LOAD';
export const SETUP_PACKAGE = 'SETUP_PACKAGE';
export const SETUP_VERIFY = 'SETUP_VERIFY';
