export const EDITOR_DEVTOOLS_TOGGLE = 'EDITOR_DEVTOOLS_TOGGLE';
export const EDITOR_INSERT = 'EDITOR_INSERT';
export const EDITOR_OPEN = 'EDITOR_OPEN';
export const EDITOR_SAVE = 'EDITOR_SAVE';
export const EDITOR_SCROLL = 'EDITOR_SCROLL';
export const EDITOR_SET = 'EDITOR_SET';
export const EDITOR_WRITE_FILE_FROM_CONTENT = 'EDITOR_WRITE_FILE_FROM_CONTENT';
export const EDITOR_WRITE_FILE_FROM_FILE = 'EDITOR_WRITE_FILE_FROM_FILE';
