// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d9b6b8e455e1ee3371a04a24d6490e1771e45b6b/react-tap-event-plugin/react-tap-event-plugin.d.ts
declare module 'react-tap-event-plugin'{
    interface StrategyOverrides {
        shouldRejectClick?: (lastTouchEventTimestamp: Date, clickEventTimestamp: Date) => boolean;
    }

    var injectTapEventPlugin: (strategyOverrides?: StrategyOverrides) => void;

    export = injectTapEventPlugin;
}
