export const TUTORIALS_FIND = 'TUTORIALS_FIND';
export const TUTORIALS_UPDATE = 'TUTORIALS_UPDATE';
export const TUTORIAL_UPDATE = 'TUTORIAL_UPDATE';
export const TUTORIAL_VERSION = 'TUTORIAL_VERSION';
