"use strict";
exports.COMPLETE_PAGE = 'COMPLETE_PAGE';
exports.COMPLETE_TUTORIAL = 'COMPLETE_TUTORIAL';
exports.PAGE_SET = 'PAGE_SET';
exports.PROGRESS_LOAD = 'PROGRESS_LOAD';
exports.PROGRESS_PAGE_POSITION_LOAD = 'PROGRESS_PAGE_POSITION_LOAD';
exports.SETUP_PACKAGE = 'SETUP_PACKAGE';
exports.SETUP_VERIFY = 'SETUP_VERIFY';
