export const PROGRESS_COMPLETE_PAGE = 'PROGRESS_COMPLETE_PAGE';
export const PROGRESS_COMPLETE_TUTORIAL = 'PROGRESS_COMPLETE_TUTORIAL';
export const PROGRESS_LOAD = 'PROGRESS_LOAD';
export const PROGRESS_PAGE_POSITION = 'PROGRESS_PAGE_POSITION';
export const PROGRESS_RESET = 'PROGRESS_RESET';