"use strict";
exports.PROGRESS_COMPLETE_PAGE = 'PROGRESS_COMPLETE_PAGE';
exports.PROGRESS_COMPLETE_TUTORIAL = 'PROGRESS_COMPLETE_TUTORIAL';
exports.PROGRESS_LOAD = 'PROGRESS_LOAD';
exports.PROGRESS_PAGE_POSITION = 'PROGRESS_PAGE_POSITION';
exports.PROGRESS_RESET = 'PROGRESS_RESET';
//# sourceMappingURL=types.js.map