"use strict";
var page_1 = require('./page');
exports.page = page_1.default;
var page_position_1 = require('./page-position');
exports.pagePosition = page_position_1.default;
var task_actions_1 = require('./task-actions');
exports.taskActions = task_actions_1.default;
var task_tests_1 = require('./task-tests');
exports.taskTests = task_tests_1.default;
var tasks_1 = require('./tasks');
exports.tasks = tasks_1.default;
