"use strict";
exports.EDITOR_DEVTOOLS_TOGGLE = 'EDITOR_DEVTOOLS_TOGGLE';
exports.EDITOR_INSERT = 'EDITOR_INSERT';
exports.EDITOR_OPEN = 'EDITOR_OPEN';
exports.EDITOR_SAVE = 'EDITOR_SAVE';
exports.EDITOR_SET = 'EDITOR_SET';
