"use strict";
exports.EDITOR_DEVTOOLS_TOGGLE = 'EDITOR_DEVTOOLS_TOGGLE';
exports.EDITOR_INSERT = 'EDITOR_INSERT';
exports.EDITOR_OPEN = 'EDITOR_OPEN';
exports.EDITOR_SAVE = 'EDITOR_SAVE';
exports.EDITOR_SCROLL = 'EDITOR_SCROLL';
exports.EDITOR_SET = 'EDITOR_SET';
exports.EDITOR_WRITE_FILE_FROM_CONTENT = 'EDITOR_WRITE_FILE_FROM_CONTENT';
exports.EDITOR_WRITE_FILE_FROM_FILE = 'EDITOR_WRITE_FILE_FROM_FILE';
