"use strict";
var redux_1 = require('redux');
var redux_localstorage_1 = require('redux-localstorage');
var adapter = require('redux-localstorage/lib/adapters/localStorage');
var redux_localstorage_filter_1 = require('redux-localstorage-filter');
var key = 'coderoad';
var storage = redux_1.compose(redux_localstorage_filter_1.default('nested.key'))(adapter(window.localStorage));
var localStorage = redux_localstorage_1.default(storage, key);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = localStorage;
